config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources 'questions'
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :votes, as: :votable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login(user)
    session[:id] = user.id
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def create
    @user = User.find(1) # pass user session id 
    @question = @user.questions.new(question_params)
    @question.save
   
    redirect_to questions_path
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
 
    if @question.update(question_params)
      redirect_to questions_path
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
 
    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.authenticate(login_params)
    if @user
      login(@user)
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def destroy
    session[:id] = nil
    redirect_to questions_path
  end

  private
  def login_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # flash[:notice] = 'Logged in successfully.'
      login(@user)
      redirect_to questions_path
    else
      # flash[:alert] = @user.errors.full_messages
      render :new
    end
  end

  def show

  end

  def edit
    @user = User.find(session[:id])
  end

  def update
    @user = User.find(session[:id])
    if params[:password] && @user.update(user_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !!session[:id]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="padding: 20px;">
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question:</h1>

<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h1>Rails-Overflow</h1>

<%= link_to('Create New Question', new_question_path) %>

<h2>Questions:</h2>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to(question.title, question) %> - <%= link_to('Edit', edit_question_path(question.id)) %> | <%= link_to('Delete', question_path(question), method: :delete) %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Create New Question</h1>

<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<%= link_to('Home', questions_path) %>

<h1><%= @question.title %></h1>

<h2>Question: <%= @question.description %></h2>

<h3>Answers:</h3>

<!-- need list of answers and comments -->

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div >
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div >
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit %>
<% end %>